import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is not configured");
}

const adapter = new PrismaPg({
  connectionString,
});

const prisma = new PrismaClient({
  adapter,
});

const countries = [
  ["AF", "Afghanistan", "afghanistan"],
  ["AL", "Albania", "albania"],
  ["DZ", "Algeria", "algeria"],
  ["AD", "Andorra", "andorra"],
  ["AO", "Angola", "angola"],
  ["AG", "Antigua and Barbuda", "antigua-and-barbuda"],
  ["AR", "Argentina", "argentina"],
  ["AM", "Armenia", "armenia"],
  ["AU", "Australia", "australia"],
  ["AT", "Austria", "austria"],
  ["AZ", "Azerbaijan", "azerbaijan"],
  ["BS", "Bahamas", "bahamas"],
  ["BH", "Bahrain", "bahrain"],
  ["BD", "Bangladesh", "bangladesh"],
  ["BB", "Barbados", "barbados"],
  ["BY", "Belarus", "belarus"],
  ["BE", "Belgium", "belgium"],
  ["BZ", "Belize", "belize"],
  ["BJ", "Benin", "benin"],
  ["BT", "Bhutan", "bhutan"],
  ["BO", "Bolivia", "bolivia"],
  ["BA", "Bosnia and Herzegovina", "bosnia-and-herzegovina"],
  ["BW", "Botswana", "botswana"],
  ["BR", "Brazil", "brazil"],
  ["BN", "Brunei", "brunei"],
  ["BG", "Bulgaria", "bulgaria"],
  ["BF", "Burkina Faso", "burkina-faso"],
  ["BI", "Burundi", "burundi"],
  ["CV", "Cabo Verde", "cabo-verde"],
  ["KH", "Cambodia", "cambodia"],
  ["CM", "Cameroon", "cameroon"],
  ["CA", "Canada", "canada"],
  ["CF", "Central African Republic", "central-african-republic"],
  ["TD", "Chad", "chad"],
  ["CL", "Chile", "chile"],
  ["CN", "China", "china"],
  ["CO", "Colombia", "colombia"],
  ["KM", "Comoros", "comoros"],
  ["CG", "Republic of the Congo", "republic-of-the-congo"],
  ["CD", "Democratic Republic of the Congo", "democratic-republic-of-the-congo"],
  ["CR", "Costa Rica", "costa-rica"],
  ["CI", "Côte d'Ivoire", "cote-divoire"],
  ["HR", "Croatia", "croatia"],
  ["CU", "Cuba", "cuba"],
  ["CY", "Cyprus", "cyprus"],
  ["CZ", "Czechia", "czechia"],
  ["DK", "Denmark", "denmark"],
  ["DJ", "Djibouti", "djibouti"],
  ["DM", "Dominica", "dominica"],
  ["DO", "Dominican Republic", "dominican-republic"],
  ["EC", "Ecuador", "ecuador"],
  ["EG", "Egypt", "egypt"],
  ["SV", "El Salvador", "el-salvador"],
  ["GQ", "Equatorial Guinea", "equatorial-guinea"],
  ["ER", "Eritrea", "eritrea"],
  ["EE", "Estonia", "estonia"],
  ["SZ", "Eswatini", "eswatini"],
  ["ET", "Ethiopia", "ethiopia"],
  ["FJ", "Fiji", "fiji"],
  ["FI", "Finland", "finland"],
  ["FR", "France", "france"],
  ["GA", "Gabon", "gabon"],
  ["GM", "Gambia", "gambia"],
  ["GE", "Georgia", "georgia"],
  ["DE", "Germany", "germany"],
  ["GH", "Ghana", "ghana"],
  ["GR", "Greece", "greece"],
  ["GD", "Grenada", "grenada"],
  ["GT", "Guatemala", "guatemala"],
  ["GN", "Guinea", "guinea"],
  ["GW", "Guinea-Bissau", "guinea-bissau"],
  ["GY", "Guyana", "guyana"],
  ["HT", "Haiti", "haiti"],
  ["HN", "Honduras", "honduras"],
  ["HU", "Hungary", "hungary"],
  ["IS", "Iceland", "iceland"],
  ["IN", "India", "india"],
  ["ID", "Indonesia", "indonesia"],
  ["IR", "Iran", "iran"],
  ["IQ", "Iraq", "iraq"],
  ["IE", "Ireland", "ireland"],
  ["IL", "Israel", "israel"],
  ["IT", "Italy", "italy"],
  ["JM", "Jamaica", "jamaica"],
  ["JP", "Japan", "japan"],
  ["JO", "Jordan", "jordan"],
  ["KZ", "Kazakhstan", "kazakhstan"],
  ["KE", "Kenya", "kenya"],
  ["KI", "Kiribati", "kiribati"],
  ["KP", "North Korea", "north-korea"],
  ["KR", "South Korea", "south-korea"],
  ["KW", "Kuwait", "kuwait"],
  ["KG", "Kyrgyzstan", "kyrgyzstan"],
  ["LA", "Laos", "laos"],
  ["LV", "Latvia", "latvia"],
  ["LB", "Lebanon", "lebanon"],
  ["LS", "Lesotho", "lesotho"],
  ["LR", "Liberia", "liberia"],
  ["LY", "Libya", "libya"],
  ["LI", "Liechtenstein", "liechtenstein"],
  ["LT", "Lithuania", "lithuania"],
  ["LU", "Luxembourg", "luxembourg"],
  ["MG", "Madagascar", "madagascar"],
  ["MW", "Malawi", "malawi"],
  ["MY", "Malaysia", "malaysia"],
  ["MV", "Maldives", "maldives"],
  ["ML", "Mali", "mali"],
  ["MT", "Malta", "malta"],
  ["MH", "Marshall Islands", "marshall-islands"],
  ["MR", "Mauritania", "mauritania"],
  ["MU", "Mauritius", "mauritius"],
  ["MX", "Mexico", "mexico"],
  ["FM", "Micronesia", "micronesia"],
  ["MD", "Moldova", "moldova"],
  ["MC", "Monaco", "monaco"],
  ["MN", "Mongolia", "mongolia"],
  ["ME", "Montenegro", "montenegro"],
  ["MA", "Morocco", "morocco"],
  ["MZ", "Mozambique", "mozambique"],
  ["MM", "Myanmar", "myanmar"],
  ["NA", "Namibia", "namibia"],
  ["NR", "Nauru", "nauru"],
  ["NP", "Nepal", "nepal"],
  ["NL", "Netherlands", "netherlands"],
  ["NZ", "New Zealand", "new-zealand"],
  ["NI", "Nicaragua", "nicaragua"],
  ["NE", "Niger", "niger"],
  ["NG", "Nigeria", "nigeria"],
  ["MK", "North Macedonia", "north-macedonia"],
  ["NO", "Norway", "norway"],
  ["OM", "Oman", "oman"],
  ["PK", "Pakistan", "pakistan"],
  ["PW", "Palau", "palau"],
  ["PS", "Palestine", "palestine"],
  ["PA", "Panama", "panama"],
  ["PG", "Papua New Guinea", "papua-new-guinea"],
  ["PY", "Paraguay", "paraguay"],
  ["PE", "Peru", "peru"],
  ["PH", "Philippines", "philippines"],
  ["PL", "Poland", "poland"],
  ["PT", "Portugal", "portugal"],
  ["QA", "Qatar", "qatar"],
  ["RO", "Romania", "romania"],
  ["RU", "Russia", "russia"],
  ["RW", "Rwanda", "rwanda"],
  ["KN", "Saint Kitts and Nevis", "saint-kitts-and-nevis"],
  ["LC", "Saint Lucia", "saint-lucia"],
  ["VC", "Saint Vincent and the Grenadines", "saint-vincent-and-the-grenadines"],
  ["WS", "Samoa", "samoa"],
  ["SM", "San Marino", "san-marino"],
  ["ST", "Sao Tome and Principe", "sao-tome-and-principe"],
  ["SA", "Saudi Arabia", "saudi-arabia"],
  ["SN", "Senegal", "senegal"],
  ["RS", "Serbia", "serbia"],
  ["SC", "Seychelles", "seychelles"],
  ["SL", "Sierra Leone", "sierra-leone"],
  ["SG", "Singapore", "singapore"],
  ["SK", "Slovakia", "slovakia"],
  ["SI", "Slovenia", "slovenia"],
  ["SB", "Solomon Islands", "solomon-islands"],
  ["SO", "Somalia", "somalia"],
  ["ZA", "South Africa", "south-africa"],
  ["SS", "South Sudan", "south-sudan"],
  ["ES", "Spain", "spain"],
  ["LK", "Sri Lanka", "sri-lanka"],
  ["SD", "Sudan", "sudan"],
  ["SR", "Suriname", "suriname"],
  ["SE", "Sweden", "sweden"],
  ["CH", "Switzerland", "switzerland"],
  ["SY", "Syria", "syria"],
  ["TJ", "Tajikistan", "tajikistan"],
  ["TZ", "Tanzania", "tanzania"],
  ["TH", "Thailand", "thailand"],
  ["TL", "Timor-Leste", "timor-leste"],
  ["TG", "Togo", "togo"],
  ["TO", "Tonga", "tonga"],
  ["TT", "Trinidad and Tobago", "trinidad-and-tobago"],
  ["TN", "Tunisia", "tunisia"],
  ["TR", "Türkiye", "turkiye"],
  ["TM", "Turkmenistan", "turkmenistan"],
  ["TV", "Tuvalu", "tuvalu"],
  ["UG", "Uganda", "uganda"],
  ["UA", "Ukraine", "ukraine"],
  ["AE", "United Arab Emirates", "united-arab-emirates"],
  ["GB", "United Kingdom", "united-kingdom"],
  ["US", "United States", "united-states"],
  ["UY", "Uruguay", "uruguay"],
  ["UZ", "Uzbekistan", "uzbekistan"],
  ["VU", "Vanuatu", "vanuatu"],
  ["VA", "Holy See", "holy-see"],
  ["VE", "Venezuela", "venezuela"],
  ["VN", "Vietnam", "vietnam"],
  ["YE", "Yemen", "yemen"],
  ["ZM", "Zambia", "zambia"],
  ["ZW", "Zimbabwe", "zimbabwe"],
] as const;

async function main() {
  for (const [code, name, slug] of countries) {
    await prisma.country.upsert({
      where: { code },
      update: {
        name,
        slug,
        active: true,
      },
      create: {
        code,
        name,
        slug,
        active: true,
      },
    });
  }

  console.log(`Seeded ${countries.length} countries.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
